package com.teamscale.report.testwise.model.builder

import com.teamscale.client.TestDetails
import com.teamscale.report.testwise.model.ETestExecutionResult
import com.teamscale.report.testwise.model.TestExecution
import com.teamscale.report.testwise.model.TestInfo

/** Generic container of all information about a specific test including details, execution info and coverage.
 * @param uniformPath Unique name of the test case by using a path like hierarchical description, which can be shown in the UI.
 */
class TestInfoBuilder(val uniformPath: String) {
	/**
	 * Path to the source of the method. Will be equal to uniformPath in most cases, but e.g. @Test methods in a base
	 * class will have the sourcePath pointing to the base class which contains the actual implementation whereas
	 * uniformPath will contain the class name of the most specific subclass, from where it was actually executed.
	 */
	private var sourcePath: String? = null

	/**
	 * Some kind of content to tell whether the test specification has changed. Can be revision number or hash over the
	 * specification or similar.
	 */
	private var content: String? = null

	/** Duration of the execution in milliseconds.  */
	private var durationSeconds: Double? = null

	/** The actual execution result state.  */
	private var result: ETestExecutionResult? = null

	/**
	 * Optional message given for test failures (normally contains a stack trace). May be `null`.
	 */
	private var message: String? = null

	/** Coverage generated by this test.  */
	private var coverage: TestCoverageBuilder? = null

	/** Returns true if there is no coverage for the test yet.  */
	val isEmpty: Boolean
		get() = coverage?.isEmpty == true

	/** Sets the test details fields.  */
	fun setDetails(details: TestDetails) {
		sourcePath = details.sourcePath
		content = details.content
	}

	/**
	 * Adds a test execution. A test may be executed more than once, e.g. once per parameter set of an enclosing
	 * `@ParameterizedClass`, in which case the executions are aggregated: the durations are summed up and the most
	 * severe of the results wins, so that a failure in any of them is not hidden by a later successful execution.
	 */
	fun addExecution(execution: TestExecution) {
		durationSeconds = (durationSeconds ?: 0.0) + execution.durationSeconds
		val previousResult = result
		if (previousResult == null || (execution.result != null && execution.result > previousResult)) {
			result = execution.result
		}
		message = listOfNotNull(message, execution.message).takeIf { it.isNotEmpty() }?.joinToString("\n\n")
	}

	/** Adds coverage of the test, merging it with any coverage that was already added for it.  */
	fun addCoverage(coverage: TestCoverageBuilder) {
		val existingCoverage = this.coverage
		if (existingCoverage == null) {
			this.coverage = coverage
		} else {
			existingCoverage.addAll(coverage.files)
		}
	}

	/** Builds a [TestInfo] object of the data in this container.  */
	fun build() =
		TestInfo(
			uniformPath, sourcePath, content, durationSeconds, result, message
		).apply {
			paths.addAll(coverage?.paths ?: emptyList())
		}
}
