package com.teamscale.report.jacoco

import com.teamscale.report.EDuplicateClassFileBehavior
import com.teamscale.report.jacoco.dump.Dump
import com.teamscale.report.util.ClasspathWildcardIncludeFilter
import com.teamscale.test.TestDataBase
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.jacoco.core.data.ExecutionData
import org.jacoco.core.data.ExecutionDataStore
import org.jacoco.core.data.SessionInfo
import org.jacoco.core.internal.data.CRC64
import org.junit.jupiter.api.Test
import org.mockito.Mockito
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Paths

/** Tests report generation with and without duplicate classes.  */
class JaCoCoXmlReportGeneratorTest : TestDataBase() {
	/** Ensures that the normal case (no duplicated classes) runs without exceptions.  */
	@Test
	fun testNormalCaseThrowsNoException() {
		try {
			runGenerator("no-duplicates", EDuplicateClassFileBehavior.FAIL)
		} catch (e: EmptyReportException) {
			// An empty report exception is thrown here because we did not configure the correct class IDs to match the
			// artificial coverage generated by createDummyDump to the actual class file. Since we are only testing for
			// IllegalStateExceptions resulting from duplicated, non-identical class files, and don't care about empty
			// reports here. Therefore we catch this exception to avoid letting the test fail because of it.
		}
	}

	/** Ensures that two identical duplicate classes do not cause problems.  */
	@Test
	fun testIdenticalClassesShouldNotThrowException() {
		try {
			runGenerator("identical-duplicate-classes", EDuplicateClassFileBehavior.FAIL)
		} catch (e: EmptyReportException) {
			// An empty report exception is thrown here because we did not configure the correct class IDs to match the
			// artificial coverage generated by createDummyDump to the actual class file. Since we are only testing for
			// IllegalStateExceptions resulting from duplicated, non-identical class files, and don't care about empty
			// reports here. Therefore we catch this exception to avoid letting the test fail because of it.
		}
	}

	/**
	 * Ensures that two non-identical, duplicate classes cause an exception to be thrown.
	 */
	@Test
	fun testDifferentClassesWithTheSameNameShouldThrowException() {
		assertThatThrownBy {
			runGenerator(
				"different-duplicate-classes",
				EDuplicateClassFileBehavior.FAIL
			)
		}.isExactlyInstanceOf(IOException::class.java)
			.hasCauseExactlyInstanceOf(IllegalStateException::class.java)
	}

	/**
	 * Ensures that two non-identical, duplicate classes do not cause an exception to be thrown if the ignore-duplicates
	 * flag is set.
	 */
	@Test
	fun testDifferentClassesWithTheSameNameShouldNotThrowExceptionIfFlagIsSet() {
		try {
			runGenerator("different-duplicate-classes", EDuplicateClassFileBehavior.IGNORE)
		} catch (e: EmptyReportException) {
			// An empty report exception is thrown here because we did not configure the correct class IDs to match the
			// artificial coverage generated by createDummyDump to the actual class file. Since we are only testing for
			// IllegalStateExceptions resulting from duplicated, non-identical class files, and don't care about empty
			// reports here. Therefore we catch this exception to avoid letting the test fail because of it.
		}
	}

	/**
	 * Ensures that two non-identical, duplicate classes in separate archives (directories) do not cause an exception
	 * with the default WARN behavior. This tests the scenario where the same class exists in multiple JARs/WARs,
	 * for example, during an application server reload where both old and new deployments coexist.
	 */
	@Test
	fun testDuplicateClassesAcrossSeparateArchivesShouldNotCrashWithWarn() {
		try {
			runGeneratorWithMultipleArchives(
				"different-duplicate-classes",
				EDuplicateClassFileBehavior.WARN
			)
		} catch (e: EmptyReportException) {
			// Expected: we don't configure matching class IDs. We only verify no IllegalStateException is thrown.
		}
	}

	/**
	 * Ensures that two non-identical, duplicate classes in separate archives (directories) cause an exception
	 * when FAIL behavior is configured.
	 */
	@Test
	fun testDuplicateClassesAcrossSeparateArchivesShouldThrowWithFail() {
		assertThatThrownBy {
			runGeneratorWithMultipleArchives(
				"different-duplicate-classes",
				EDuplicateClassFileBehavior.FAIL
			)
		}.isExactlyInstanceOf(IOException::class.java)
			.hasCauseExactlyInstanceOf(IllegalStateException::class.java)
	}

	/**
	 * Verifies that reusing a single [JaCoCoXmlReportGenerator] across multiple dumps works even when the class files
	 * change between dumps (for example, due to an application server reload). The generator creates a fresh
	 * [CoverageBuilder] for each dump via its supplier, so no state leaks between dumps.
	 */
	@Test
	fun testReusedGeneratorHandlesClassFileChangesBetweenDumps() {
		val sourceA = useTestFile("different-duplicate-classes" + File.separator + "a")
		val sourceB = useTestFile("different-duplicate-classes" + File.separator + "b")

		// Create a temp directory that simulates the JaCoCo class dump directory
		val tempDir = Files.createTempDirectory("reuse-generator-test").toFile()

		try {
			// Start with version A of TestClass
			sourceA.listFiles()!!.forEach { it.copyTo(File(tempDir, it.name)) }

			val generator = JaCoCoXmlReportGenerator(
				listOf(tempDir),
				ClasspathWildcardIncludeFilter(null, null),
				EDuplicateClassFileBehavior.WARN,
				false,
				Mockito.mock()
			)

			// First dump succeeds
			try {
				generator.convertSingleDumpToReport(
					createDummyDump(), File(tempDir, "output-1.xml")
				)
			} catch (e: EmptyReportException) {
				// Expected: dummy dump class IDs don't match actual class files
			}

			// Replace with version B of TestClass (different bytecode, different CRC64)
			tempDir.listFiles()!!.filter { it.name != "output-1.xml" }.forEach { it.delete() }
			sourceB.listFiles()!!.forEach { it.copyTo(File(tempDir, it.name)) }

			// Second dump on the SAME generator succeeds because each dump gets a fresh CoverageBuilder
			try {
				generator.convertSingleDumpToReport(
					createDummyDump(), File(tempDir, "output-2.xml")
				)
			} catch (e: EmptyReportException) {
				// Expected: dummy dump class IDs don't match actual class files
			}
		} finally {
			tempDir.deleteRecursively()
		}
	}

	@Test
	fun testEmptyCoverageFileThrowsException() {
		val testFolderName = "empty-report-handling"
		val classId = calculateClassId(testFolderName, "TestClass.class")
		assertThatThrownBy {
			runGenerator(
				testFolderName,
				EDuplicateClassFileBehavior.IGNORE,
				false,
				ClasspathWildcardIncludeFilter("some.package.*", null),
				createDummyDump(classId)
			)
		}.isExactlyInstanceOf(EmptyReportException::class.java)
	}

	@Test
	@Throws(IOException::class, EmptyReportException::class)
	fun testNonEmptyCoverageFileDoesNotThrowException() {
		val testFolderName = "empty-report-handling"
		val classId = calculateClassId(testFolderName, "TestClass.class")
		runGenerator(
			testFolderName, EDuplicateClassFileBehavior.IGNORE, false,
			ClasspathWildcardIncludeFilter("*", null), createDummyDump(classId)
		)
	}

	/** Ensures that uncovered classes are removed from the report if ignore-uncovered-classes is set.  */
	@Test
	fun testShrinking() {
		val testFolderName = "ignore-uncovered-classes"
		val classId = calculateClassId(testFolderName, "TestClass.class")
		val stream = ByteArrayOutputStream()

		runGenerator(
			testFolderName, EDuplicateClassFileBehavior.FAIL, true,
			ClasspathWildcardIncludeFilter("*", null),
			createDummyDump(classId)
		).copyStream(stream)

		val xmlString = stream.toString(StandardCharsets.UTF_8.name())
		assertThat(xmlString).contains("TestClass")
		assertThat(xmlString).doesNotContain("TestClassTwo")
		assertThat(xmlString).doesNotContain("ITestInterface")
	}

	/** Ensures that uncovered classes are contained in the report if ignore-uncovered-classes is not set.  */
	@Test
	fun testNonShrinking() {
		val testFolderName = "ignore-uncovered-classes"
		val classId = calculateClassId(testFolderName, "TestClass.class")
		val stream = ByteArrayOutputStream()

		runGenerator(
			testFolderName, EDuplicateClassFileBehavior.FAIL, false,
			ClasspathWildcardIncludeFilter("*", null),
			createDummyDump(classId)
		).copyStream(stream)

		val xmlString = stream.toString(StandardCharsets.UTF_8.name())
		assertThat(xmlString).contains("TestClassTwo")
	}

	@Throws(IOException::class)
	private fun calculateClassId(testFolderName: String, classFileName: String): Long {
		val classFile = useTestFile(testFolderName + File.separator + classFileName)
		return CRC64.classId(Files.readAllBytes(classFile.toPath()))
	}

	/** Runs the report generator with default values and without ignoring uncovered classes.  */
	@Throws(IOException::class, EmptyReportException::class)
	private fun runGenerator(
		testDataFolder: String,
		duplicateClassFileBehavior: EDuplicateClassFileBehavior,
		ignoreUncoveredClasses: Boolean = false,
		filter: ClasspathWildcardIncludeFilter = ClasspathWildcardIncludeFilter(null, null),
		dump: Dump = createDummyDump()
	): CoverageFile {
		val classFileFolder = useTestFile(testDataFolder)
		val currentTime = System.currentTimeMillis()
		val outputFilePath = "test-coverage-$currentTime.xml"
		return JaCoCoXmlReportGenerator(
			listOf(classFileFolder),
			filter,
			duplicateClassFileBehavior,
			ignoreUncoveredClasses,
			Mockito.mock()
		).convertSingleDumpToReport(dump, Paths.get(outputFilePath).toFile())
	}

	/**
	 * Runs the report generator with each subdirectory of the test data folder as a separate archive entry.
	 * This simulates the case where the same class exists in multiple JARs/WARs (for example, after an application
	 * server reload where both old and new deployments coexist on the classpath).
	 */
	@Throws(IOException::class, EmptyReportException::class)
	private fun runGeneratorWithMultipleArchives(
		testDataFolder: String,
		duplicateClassFileBehavior: EDuplicateClassFileBehavior,
		dump: Dump = createDummyDump()
	): CoverageFile {
		val parentFolder = useTestFile(testDataFolder)
		val subdirectories = parentFolder.listFiles { file -> file.isDirectory }?.toList()
			?: error("No subdirectories found in $parentFolder")
		val currentTime = System.currentTimeMillis()
		val outputFilePath = "test-coverage-multi-archive-$currentTime.xml"
		return JaCoCoXmlReportGenerator(
			subdirectories,
			ClasspathWildcardIncludeFilter(null, null),
			duplicateClassFileBehavior,
			false,
			Mockito.mock()
		).convertSingleDumpToReport(dump, Paths.get(outputFilePath).toFile())
	}

	companion object {
		/**
		 * Creates a fake dump with the specified class ID. The class ID can currently be calculated with [org.jacoco.core.internal.data.CRC64.classId].
		 * This might change in the future, as it's considered an [implementation detail of JaCoCo](https://www.jacoco.org/jacoco/trunk/doc/classids.html))
		 */
		private fun createDummyDump(classId: Long = 123): Dump {
			val store = ExecutionDataStore()
			store.put(ExecutionData(classId, "TestClass", booleanArrayOf(true, true, true)))
			val info = SessionInfo("session-id", 124L, 125L)
			return Dump(info, store)
		}
	}
}
